###Find all offices
GET http://localhost:3000/api/offices


### Obtain an office by ID
@idOffice = ({office.response.body.data.id})

GET http://localhost:3000/api/offices/1

### Create a new office
# @name CreateOffice
POST http://localhost:3000/api/offices
Content-Type: application/json

{
    "closingTime": "18:00",
    "openingTime": "08:00",
    "description": "Consultorio Zona Norte",
    "city": "1"
}

### Create a new office with invalid time
POST http://localhost:3000/api/offices
Content-Type: application/json

{
    "city": "2",
    "description": "oeste",
    "closingTime": "8:00",
    "openingTime": "18:00"
}

### Modify an office
PUT http://localhost:3000/api/offices/1
Content-Type: application/json

{
  "description": "Sala Roja"
}

### Modify an office with invalid time
PUT http://localhost:3000/api/offices/3
Content-Type: application/json

{
  "idOffice": "2"
}

### Delete an office
PATCH http://localhost:3000/api/offices/2
Content-Type: application/json

{
  "state": false
}