### obtener todos los provincias
GET http://localhost:3000/api/provinces


### obtener una provincia
GET http://localhost:3000/api/provinces/01

### crear una nueva provincia
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
    "name": "Neuquen",
    "idProvince": "1974"
}

### modificar una provincia (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/provinces/01
Content-Type: application/json

{
  "name": "Tierra del Fuego"
}

### modificar un provincia (PATCH - recurso parcial)
PATCH http://localhost:3000/api/provinces/01
Content-Type: application/json

{
  "name": "Tierra del Hielo"
}

### borrar un provincia
DELETE http://localhost:3000/api/provinces/01