### GET ALL -obtener todos los provincias
GET http://localhost:3000/api/provinces

### ID
@idProvince = {{createProvince.response.body.data.idProvince}}

### GET ONE - obtener una provincia
GET http://localhost:3000/api/provinces/{{idProvince}}

### POST - crear una nueva provincia
# @name createProvince
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
  "idProvince": "05",
  "nameProvince": "Tucuman",
  "cities": []
}

### PUT - modificar una provincia
PUT http://localhost:3000/api/provinces/{{idProvince}}
Content-Type: application/json

{
  "nameProvince": "Tierra del Fuego"
}

### DELETE - borrar un provincia
DELETE http://localhost:3000/api/provinces/{{idProvince}}