### GET ALL -obtener todos los provincias
GET http://localhost:3000/api/provinces

### ID
@idProvince = {{createProvincee.response.body.data.idProvince}}

### GET ONE - obtener una provincia
GET http://localhost:3000/api/provinces/{{idProvince}}

### POST - crear una nueva provincia
# @name createProvincee
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
  "nameProvince": "Santa Cruz",
  "cities": []
}

### PUT - modificar una provincia
PUT http://localhost:3000/api/provinces/{{idProvince}}
Content-Type: application/json

{
  "nameProvince": "Tierra del Fuego"
}

### PUT - activar una provincia
PUT http://localhost:3000/api/provinces/1
Content-Type: application/json

{
  "active": true
}

### PATCH - modificar una provincia
PATCH  http://localhost:3000/api/provinces/15
Content-Type: application/json

{
  "active": true
}

