### obtener todos los personas
GET http://localhost:3000/api/people

### obtener una persona
GET http://localhost:3000/api/people/olivieri03@gmail.com

### crear una nueva persona
POST http://localhost:3000/api/people
Content-Type: application/json

{
    "email": "profesional@gmail.com",
    "docType": "dni",
    "docNumber": "222222",
    "name": "Hola",
    "surname": "Mundo",
    "phoneNumber": "123",
    "password": "1234",
    "type": "professional",
    "speciality": "TESTING"
}

### loguear una persona
POST http://localhost:3000/api/people/login
Content-Type: application/json

{
    "email": "profesional@gmail.com",
    "password": "1234"
}

### modificar una persona (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/people/profesional@gmail.com
Content-Type: application/json

{
    "docType": "pasaporte",
    "phoneNumber": "3413493887",
    "password": "1234",
    "active": false,
    "type": "professional"
}


### Eliminar request de profesional
DELETE http://localhost:3000/api/people/profesional@gmail.com

### modificar una persona (PATCH - recurso parcial)
PATCH http://localhost:3000/api/people/olivieri03@gmail.com
Content-Type: application/json

{
    "active": false
}

