### obtener todos los personas
GET http://localhost:3000/api/people

### obtener una persona
GET http://localhost:3000/api/people/olivieri03@gmail.com

### crear una nueva persona
POST http://localhost:3000/api/people
Content-Type: application/json

{
    "email": "hola6@gmail.com",
    "docType": "dni",
    "docNumber": "222222",
    "name": "Hola",
    "surname": "Mundo",
    "phoneNumber": "123",
    "password": "1234",
    "type": "admin",
    "speciality": "TESTING"
}

### loguear una persona
POST http://localhost:3000/api/people/login
Content-Type: application/json

{
    "email": "mateoprueba@gmail.com",
    "password": "mateo"
}

### modificar una persona (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/people/genaro20038@gmail.com
Content-Type: application/json

{
    "docType": "pasaporte",
    "phoneNumber": "3413493887"
}

### modificar una persona (PATCH - recurso parcial)
PATCH http://localhost:3000/api/people/olivieri03@gmail.com
Content-Type: application/json

{
    "active": false
}