### obtener todos las localidades
GET http://localhost:3000/api/cities

### ID
@id = {{createCity.response.body.data.idCity}}

### obtener una Localidad (GET ONE)
GET http://localhost:3000/api/cities/7

### crear una nueva localidad
# @name createCity
POST http://localhost:3000/api/cities
Content-Type: application/json

{
    "nameCity": "usuhaia",
    "province": "12",
    "offices" : []
}

### modificar una localidad (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/cities/4
Content-Type: application/json

{
  "state": false
}

### modificar una localidad (PATCH - recurso parcial)
PATCH http://localhost:3000/api/cities/18
Content-Type: application/json

{
  "active": false
}


### Eliminar / Reactivar localidad
PATCH http://localhost:3000/api/cities/7/toggle-state
Content-Type: application/json

{}