### obtener todos las localidades
GET http://localhost:3000/api/cities

### Obtener todas las localidades activas
GET http://localhost:3000/api/cities/active

### obtener una Localidad (GET ONE)
GET http://localhost:3000/api/cities/18

### crear una nueva localidad
POST http://localhost:3000/api/cities
Content-Type: application/json

{
    "nameCity": "Rosario",
    "province": "1",
    "offices" : []
}

### modificar una localidad (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/cities/1
Content-Type: application/json

{
  "nameCity": "Santa Cruz ciudad",
  "province": 1
}

### cambiar el estado de una ciudad)
PATCH http://localhost:3000/api/cities/4/toggle-state
Content-Type: application/json

{

}